spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_generator
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
file:
  path: "file"

security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000  # bir kun
    refresh-token:
        expiration: 604800000  # 7 kun
